from django.utils.translation import ugettext_lazy as _

LANGUAGES = (
    ('--', _('Please choose a language..')),
    ('af', _('Afrikaans')),
    ('ar', _('Arabic')),
    ('az', _('Azerbaijani')),
    ('bg', _('Bulgarian')),
    ('be', _('Belarusian')),
    ('bn', _('Bengali')),
    ('br', _('Breton')),
    ('bs', _('Bosnian')),
    ('ca', _('Catalan')),
    ('cs', _('Czech')),
    ('cy', _('Welsh')),
    ('da', _('Danish')),
    ('de', _('German')),
    ('el', _('Greek')),
    ('en', _('English')),
    ('en-gb', _('British English')),
    ('eo', _('Esperanto')),
    ('es', _('Spanish')),
    ('es-ar', _('Argentinian Spanish')),
    ('es-mx', _('Mexican Spanish')),
    ('es-ni', _('Nicaraguan Spanish')),
    ('es-ve', _('Venezuelan Spanish')),
    ('et', _('Estonian')),
    ('eu', _('Basque')),
    ('fa', _('Persian')),
    ('fi', _('Finnish')),
    ('fr', _('French')),
    ('fy-nl', _('Frisian')),
    ('ga', _('Irish')),
    ('gl', _('Galician')),
    ('he', _('Hebrew')),
    ('hi', _('Hindi')),
    ('hr', _('Croatian')),
    ('hu', _('Hungarian')),
    ('ia', _('Interlingua')),
    ('id', _('Indonesian')),
    ('is', _('Icelandic')),
    ('it', _('Italian')),
    ('ja', _('Japanese')),
    ('ka', _('Georgian')),
    ('kk', _('Kazakh')),
    ('km', _('Khmer')),
    ('kn', _('Kannada')),
    ('ko', _('Korean')),
    ('lb', _('Luxembourgish')),
    ('lt', _('Lithuanian')),
    ('lv', _('Latvian')),
    ('mk', _('Macedonian')),
    ('ml', _('Malayalam')),
    ('mn', _('Mongolian')),
    ('nb', _('Norwegian Bokmal')),
    ('ne', _('Nepali')),
    ('nl', _('Dutch')),
    ('nn', _('Norwegian Nynorsk')),
    ('pa', _('Punjabi')),
    ('pl', _('Polish')),
    ('pt', _('Portuguese')),
    ('pt-br', _('Brazilian Portuguese')),
    ('ro', _('Romanian')),
    ('ru', _('Russian')),
    ('sk', _('Slovak')),
    ('sl', _('Slovenian')),
    ('sq', _('Albanian')),
    ('sr', _('Serbian')),
    ('sr-latn', _('Serbian Latin')),
    ('sv', _('Swedish')),
    ('sw', _('Swahili')),
    ('ta', _('Tamil')),
    ('te', _('Telugu')),
    ('th', _('Thai')),
    ('tr', _('Turkish')),
    ('tt', _('Tatar')),
    ('udm', _('Udmurt')),
    ('uk', _('Ukrainian')),
    ('ur', _('Urdu')),
    ('vi', _('Vietnamese')),
    ('zh-cn', _('Simplified Chinese')),
    ('zh-tw', _('Traditional Chinese')),
)

COUNTRIES = (
    ('--', _('Please choose a country..')),
    ('AD', _('Andorra')),
    ('AE', _('United Arab Emirates')),
    ('AF', _('Afghanistan')),
    ('AG', _('Antigua & Barbuda')),
    ('AI', _('Anguilla')),
    ('AL', _('Albania')),
    ('AM', _('Armenia')),
    ('AN', _('Netherlands Antilles')),
    ('AO', _('Angola')),
    ('AQ', _('Antarctica')),
    ('AR', _('Argentina')),
    ('AS', _('American Samoa')),
    ('AT', _('Austria')),
    ('AU', _('Australia')),
    ('AW', _('Aruba')),
    ('AZ', _('Azerbaijan')),
    ('BA', _('Bosnia and Herzegovina')),
    ('BB', _('Barbados')),
    ('BD', _('Bangladesh')),
    ('BE', _('Belgium')),
    ('BF', _('Burkina Faso')),
    ('BG', _('Bulgaria')),
    ('BH', _('Bahrain')),
    ('BI', _('Burundi')),
    ('BJ', _('Benin')),
    ('BM', _('Bermuda')),
    ('BN', _('Brunei Darussalam')),
    ('BO', _('Bolivia')),
    ('BR', _('Brazil')),
    ('BS', _('Bahama')),
    ('BT', _('Bhutan')),
    ('BV', _('Bouvet Island')),
    ('BW', _('Botswana')),
    ('BY', _('Belarus')),
    ('BZ', _('Belize')),
    ('CA', _('Canada')),
    ('CC', _('Cocos (Keeling) Islands')),
    ('CF', _('Central African Republic')),
    ('CG', _('Congo')),
    ('CH', _('Switzerland')),
    ('CI', _('Ivory Coast')),
    ('CK', _('Cook Iislands')),
    ('CL', _('Chile')),
    ('CM', _('Cameroon')),
    ('CN', _('China')),
    ('CO', _('Colombia')),
    ('CR', _('Costa Rica')),
    ('CU', _('Cuba')),
    ('CV', _('Cape Verde')),
    ('CX', _('Christmas Island')),
    ('CY', _('Cyprus')),
    ('CZ', _('Czech Republic')),
    ('DE', _('Germany')),
    ('DJ', _('Djibouti')),
    ('DK', _('Denmark')),
    ('DM', _('Dominica')),
    ('DO', _('Dominican Republic')),
    ('DZ', _('Algeria')),
    ('EC', _('Ecuador')),
    ('EE', _('Estonia')),
    ('EG', _('Egypt')),
    ('EH', _('Western Sahara')),
    ('ER', _('Eritrea')),
    ('ES', _('Spain')),
    ('ET', _('Ethiopia')),
    ('FI', _('Finland')),
    ('FJ', _('Fiji')),
    ('FK', _('Falkland Islands (Malvinas)')),
    ('FM', _('Micronesia')),
    ('FO', _('Faroe Islands')),
    ('FR', _('France')),
    ('FX', _('France, Metropolitan')),
    ('GA', _('Gabon')),
    ('GB', _('United Kingdom (Great Britain)')),
    ('GD', _('Grenada')),
    ('GE', _('Georgia')),
    ('GF', _('French Guiana')),
    ('GH', _('Ghana')),
    ('GI', _('Gibraltar')),
    ('GL', _('Greenland')),
    ('GM', _('Gambia')),
    ('GN', _('Guinea')),
    ('GP', _('Guadeloupe')),
    ('GQ', _('Equatorial Guinea')),
    ('GR', _('Greece')),
    ('GS', _('South Georgia and the South Sandwich Islands')),
    ('GT', _('Guatemala')),
    ('GU', _('Guam')),
    ('GW', _('Guinea-Bissau')),
    ('GY', _('Guyana')),
    ('HK', _('Hong Kong')),
    ('HM', _('Heard & McDonald Islands')),
    ('HN', _('Honduras')),
    ('HR', _('Croatia')),
    ('HT', _('Haiti')),
    ('HU', _('Hungary')),
    ('ID', _('Indonesia')),
    ('IE', _('Ireland')),
    ('IL', _('Israel')),
    ('IN', _('India')),
    ('IO', _('British Indian Ocean Territory')),
    ('IQ', _('Iraq')),
    ('IR', _('Islamic Republic of Iran')),
    ('IS', _('Iceland')),
    ('IT', _('Italy')),
    ('JM', _('Jamaica')),
    ('JO', _('Jordan')),
    ('JP', _('Japan')),
    ('KE', _('Kenya')),
    ('KG', _('Kyrgyzstan')),
    ('KH', _('Cambodia')),
    ('KI', _('Kiribati')),
    ('KM', _('Comoros')),
    ('KN', _('St. Kitts and Nevis')),
    ('KP', _('Korea, Democratic People\'s Republic of')),
    ('KR', _('Korea, Republic of')),
    ('KW', _('Kuwait')),
    ('KY', _('Cayman Islands')),
    ('KZ', _('Kazakhstan')),
    ('LA', _('Lao People\'s Democratic Republic')),
    ('LB', _('Lebanon')),
    ('LC', _('Saint Lucia')),
    ('LI', _('Liechtenstein')),
    ('LK', _('Sri Lanka')),
    ('LR', _('Liberia')),
    ('LS', _('Lesotho')),
    ('LT', _('Lithuania')),
    ('LU', _('Luxembourg')),
    ('LV', _('Latvia')),
    ('LY', _('Libyan Arab Jamahiriya')),
    ('MA', _('Morocco')),
    ('MC', _('Monaco')),
    ('MD', _('Moldova, Republic of')),
    ('MG', _('Madagascar')),
    ('MH', _('Marshall Islands')),
    ('ML', _('Mali')),
    ('MN', _('Mongolia')),
    ('MM', _('Myanmar')),
    ('MO', _('Macau')),
    ('MP', _('Northern Mariana Islands')),
    ('MQ', _('Martinique')),
    ('MR', _('Mauritania')),
    ('MS', _('Monserrat')),
    ('MT', _('Malta')),
    ('MU', _('Mauritius')),
    ('MV', _('Maldives')),
    ('MW', _('Malawi')),
    ('MX', _('Mexico')),
    ('MY', _('Malaysia')),
    ('MZ', _('Mozambique')),
    ('NA', _('Namibia')),
    ('NC', _('New Caledonia')),
    ('NE', _('Niger')),
    ('NF', _('Norfolk Island')),
    ('NG', _('Nigeria')),
    ('NI', _('Nicaragua')),
    ('NL', _('Netherlands')),
    ('NO', _('Norway')),
    ('NP', _('Nepal')),
    ('NR', _('Nauru')),
    ('NU', _('Niue')),
    ('NZ', _('New Zealand')),
    ('OM', _('Oman')),
    ('PA', _('Panama')),
    ('PE', _('Peru')),
    ('PF', _('French Polynesia')),
    ('PG', _('Papua New Guinea')),
    ('PH', _('Philippines')),
    ('PK', _('Pakistan')),
    ('PL', _('Poland')),
    ('PM', _('St. Pierre & Miquelon')),
    ('PN', _('Pitcairn')),
    ('PR', _('Puerto Rico')),
    ('PT', _('Portugal')),
    ('PW', _('Palau')),
    ('PY', _('Paraguay')),
    ('QA', _('Qatar')),
    ('RE', _('Reunion')),
    ('RO', _('Romania')),
    ('RU', _('Russian Federation')),
    ('RW', _('Rwanda')),
    ('SA', _('Saudi Arabia')),
    ('SB', _('Solomon Islands')),
    ('SC', _('Seychelles')),
    ('SD', _('Sudan')),
    ('SE', _('Sweden')),
    ('SG', _('Singapore')),
    ('SH', _('St. Helena')),
    ('SI', _('Slovenia')),
    ('SJ', _('Svalbard & Jan Mayen Islands')),
    ('SK', _('Slovakia')),
    ('SL', _('Sierra Leone')),
    ('SM', _('San Marino')),
    ('SN', _('Senegal')),
    ('SO', _('Somalia')),
    ('SR', _('Suriname')),
    ('ST', _('Sao Tome & Principe')),
    ('SV', _('El Salvador')),
    ('SY', _('Syrian Arab Republic')),
    ('SZ', _('Swaziland')),
    ('TC', _('Turks & Caicos Islands')),
    ('TD', _('Chad')),
    ('TF', _('French Southern Territories')),
    ('TG', _('Togo')),
    ('TH', _('Thailand')),
    ('TJ', _('Tajikistan')),
    ('TK', _('Tokelau')),
    ('TM', _('Turkmenistan')),
    ('TN', _('Tunisia')),
    ('TO', _('Tonga')),
    ('TP', _('East Timor')),
    ('TR', _('Turkey')),
    ('TT', _('Trinidad & Tobago')),
    ('TV', _('Tuvalu')),
    ('TW', _('Taiwan, Province of China')),
    ('TZ', _('Tanzania, United Republic of')),
    ('UA', _('Ukraine')),
    ('UG', _('Uganda')),
    ('UM', _('United States Minor Outlying Islands')),
    ('US', _('United States of America')),
    ('UY', _('Uruguay')),
    ('UZ', _('Uzbekistan')),
    ('VA', _('Vatican City State (Holy See)')),
    ('VC', _('St. Vincent & the Grenadines')),
    ('VE', _('Venezuela')),
    ('VG', _('British Virgin Islands')),
    ('VI', _('United States Virgin Islands')),
    ('VN', _('Viet Nam')),
    ('VU', _('Vanuatu')),
    ('WF', _('Wallis & Futuna Islands')),
    ('WS', _('Samoa')),
    ('YE', _('Yemen')),
    ('YT', _('Mayotte')),
    ('YU', _('Yugoslavia')),
    ('ZA', _('South Africa')),
    ('ZM', _('Zambia')),
    ('ZR', _('Zaire')),
    ('ZW', _('Zimbabwe')),
)

RPG_CLASS = (
    ('--', _('I am a...')),
    ('CZ', _('Citizen')),
    ('RS', _('Researcher')),
    ('JS', _('Journalist')),
    ('CS', _('Civil Servant')),
    ('CS', _('Archivist / Librarian')),
    ('PL', _('Politician')),
    ('ER', _('Enterpreneur')),
    ('HA', _('IT expert / Hacker'))
)

EXTENSION = (
    ('--', _('Please choose an extension type..')),
    ('CF', _('Conversion to other format')),
    ('DC', _('Data Cleansing')),
    ('ME', _('Metadata Enrichment')),
    ('DE', _('Data Enrichment')),
    ('SR', _('Snapshots of real-time data')),
    ('CD', _('Combination of Datasets / Mash-ups'))
)

DATASET_STATE = (
    ('AA', _('Awaiting Approval')),
    ('AP', _('Approved')),
    ('RE', _('Rejected')),
)

CATEGORIES = (
    ('AG', _('Agriculture')),
    ('ART', _('Arts, Recreation and Travel')),
    ('BFI', _('Banking, Finance and Insurance')),
    ('BDMD', _('Births, Deaths, Marriages and Divorces')),
    ('BE', _('Business / Enterprises')),
    ('CE', _('Census')),
    ('CH', _('Construction and Housing')),
    ('CO', _('Contributors')),
    ('DI', _('Diplomacy')),
    ('EC', _('Economic')),
    ('ED', _('Education')),
    ('EL', _('Elections')),
    ('EM', _('Employment')),
    ('EU', _('Energy and Utilities')),
    ('EN', _('Environment')),
    ('FA', _('Farming')),
    ('FI', _('Financials')),
    ('FCA', _('Foreign Commerce and Aid')),
    ('FT', _('Foreign Trade')),
    ('GE', _('Geography and Environment')),
    ('HN', _('Health and Nutrition')),
    ('IEPW', _('Income, Expenditures, Poverty, and Wealth')),
    ('IC', _('Information and Communications')),
    ('IS', _('International Statistics')),
    ('LFEE', _('Labor Force, Employment, and Earnings')),
    ('LECP', _('Law Enforcement, Courts, and Prisons')),
    ('MA', _('Manufactures')),
    ('MI', _('Military')),
    ('NSVA', _('National Security and Veterans Affairs')),
    ('NR', _('Natural Resources')),
    ('OT', _('Other')),
    ('PO', _('Population')),
    ('PR', _('Prices')),
    ('PABF', _('Public Agencies Budget and Finances')),
    ('PAE', _('Public Agencies Employment')),
    ('ST', _('Science and Technology')),
    ('SIHS', _('Social Insurance and Human Services')),
    ('SP', _('Space')),
    ('TA', _('Taxation')),
    ('TR', _('Transportation')),
    ('WE', _('Welfare')),
    ('WRT', _('Wholesale and Retail Trade'))
)

LICENSES = (
    ('cc-by', 'OKD Compliant::Creative Commons Attribution'),
    ('cc-by-sa', 'OKD Compliant::Creative Commons Share-Alike'),
    ('apache', 'OSI Approved::Apache Software License'),
    ('apache2.0', 'OSI Approved::Apache License, 2.0'),
    ('bsd-license', 'OSI Approved::New and Simplified BSD licenses'),
    ('ca-tosl1.1', 'OSI Approved::Computer Associates Trusted Open Source License 1.1'),
    ('cc-nc', 'Non-OKD Compliant::Creative Commons Non-Commercial (Any)'),
    ('cc-zero', 'OKD Compliant::Creative Commons CCZero'),
    ('eclipse-1.0', 'OSI Approved::Eclipse Public License'),
    ('gfdl', 'OKD Compliant::GNU Free Documentation License'),
    ('gpl-2.0', 'OSI Approved::GNU General Public License (GPL)'),
    ('gpl-3.0', 'OSI Approved::GNU General Public License version 3.0 (GPLv3)'),
    ('mit-license', 'OSI Approved::MIT license'),
    ('mozilla', 'OSI Approved::Mozilla Public License 1.0 (MPL)'),
    ('mozilla1.1', 'OSI Approved::Mozilla Public License 1.1 (MPL)'),
    ('odc-odbl', 'OKD Compliant::Open Data Commons Open Database License (ODbL)'),
    ('odc-pddl', 'OKD Compliant::Open Data Commons Public Domain Dedication and Licence (PDDL)'),
    ('W3C', 'OSI Approved::W3C License'), ('other-closed', 'Other::Proprietary License'),
    ('other-nc', 'Other::Non-commercial License'),
    ('notspecified', 'Other::License Not Specified'),
    ('uk-ogl', 'UK Open Government Licence (OGL)'),
    ('W3C', 'OSI Approved::W3C License'),
    ('OGL', 'Open Government Licence'),
    ('FOL', 'French Open Licence'),
    ('EUR', 'Eurostat Copyright/Licence Policy'),
    ('GPSI', 'General PSI licence'),
    ('IODL', 'Italian Open Data Licence'),
    ('NLOD', 'Norwegian Licence for Open Government Data (NLOD)')
)

EXTENSION_DESCRIPTION = {
    'CF': '<img width="68px" height="68px" src="/s/imgs/r_CF.png"/><div><b>Conversion to other format</b></div><div>Convert the original dataset to another format (e.g. from .pdf to excel)</div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'DC': ' <img width="68px" height="68px" src="/s/imgs/r_DC.png"/><div><b>Data Cleansing</b></div><div>Data cleansing, data cleaning or data scrubbing is the process of detecting and correcting (or removing) corrupt or inaccurate records from a record set, table, or database. Used mainly in databases, the term refers to identifying incomplete, incorrect, inaccurate, irrelevant, etc. parts of the data and then replacing, modifying, or deleting this dirty data</div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'ME': ' <img width="68px" height="68px" src="/s/imgs/r_ME.png"/><div><b>Metadata Enrichment</b></div><div>Metadata Enrichment is the process of adding more information to the metadata describing the dataset</div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'DE': '<img width="68px" height="68px" src="/s/imgs/r_DE.png"/><div><b>Data Enrichment</b></div><div>Data Enrichment is a value adding process, where external data from multiple sources is added to the existing dataset to enhance the quality and richness of the data.This process provides more information of the dataset to the users</div><div style="margin-top:15px">You can read more about the recommended Data Enrichment procedures <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'SR': '<img width="68px" height="68px" src="/s/imgs/r_SR.png"/><div><b>Snapshots of real-time data</b></div><div>Snapshots of real-time data is the process of capturing a snapshot of dynamic, real-time data. The snapshots indicate the captured time period of the datasets </div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'CD': '<img width="68px" height="68px" src="/s/imgs/r_CD.png"/><div><b>Combination of Datasets / Mash-ups</b></div><div>Combine, link and mashup datasets coming from different sources to create interesting datasets!</div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>'
}

REQUEST_DESCRIPTION = {
    'SD': '<img width="68px" height="68px" src="/s/imgs/r_SD.png"/><div><b>Looking for a dataset</b></div><div>Looking for a dataset that you cannot find anywhere else? Ask for community to get it for you!</div>',
    'CF': '<img width="68px" height="68px" src="/s/imgs/r_CF.png"/><div><b>Conversion to other format Request</b></div><div>Convert the original dataset to another format (e.g. from .pdf to excel)</div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'DC': ' <img width="68px" height="68px" src="/s/imgs/r_DC.png"/><div><b>Data Cleansing Request</b></div><div>Data cleansing, data cleaning or data scrubbing is the process of detecting and correcting (or removing) corrupt or inaccurate records from a record set, table, or database. Used mainly in databases, the term refers to identifying incomplete, incorrect, inaccurate, irrelevant, etc. parts of the data and then replacing, modifying, or deleting this dirty data</div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'ME': ' <img width="68px" height="68px" src="/s/imgs/r_ME.png"/><div><b>Metadata Enrichment Request</b></div><div>Metadata Enrichment is the process of adding more information to the metadata describing the dataset</div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'DE': '<img width="68px" height="68px" src="/s/imgs/r_DE.png"/><div><b>Data Enrichment Request</b></div><div>Data Enrichment is a value adding process, where external data from multiple sources is added to the existing dataset to enhance the quality and richness of the data.This process provides more information of the dataset to the users</div><div style="margin-top:15px">You can read more about the recommended Data Enrichment procedures <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'SR': '<img width="68px" height="68px" src="/s/imgs/r_SR.png"/><div><b>Snapshots of real-time data Request</b></div><div>Snapshots of real-time data is the process of capturing a snapshot of dynamic, real-time data. The snapshots indicate the captured time period of the datasets </div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'CD': '<img width="68px" height="68px" src="/s/imgs/r_CD.png"/><div><b>Combination of Datasets / Mash-ups</b></div><div>Combine, link and mashup datasets coming from different sources to create interesting datasets!</div><div style="margin-top:15px">You can read more about this <a style="color:#DE4F15" href="/wiki/data_curation" >here</a></div>',
    'DV': '<img width="68px" height="68px" src="/s/imgs/r_DV.png"/><div><b>Data Verification Request</b></div><div>You are not certain about the authenticity, integrity and quality of a dataset? Ask the community to verify! </div>',
    'FI': '<img width="68px" height="68px" src="/s/imgs/r_FI.png"/><div><b>Freedom of Information Request</b></div><div>Freedom of Information Request involves requesting any public sector organisation to liberate recorded data they have on any subject.Anyone can make a request for information, there are no restrictions on your age, nationality or where you live.</div>'
}

TEMPORAL_GRANULARITY = (
    ('Y', _('Year')),
    ('M', _('Month')),
    ('W', _('Week')),
    ('D', _('Day')),
    ('H', _('Hour')),
)

SPATIAL_GRANULARITY = (
    ('WO', _('Worldwide')),
    ('CO', _('Continent')),
    ('PU', _('Political Union')),
    ('COU', _('Country')),
    ('RE', _('Region')),
    ('LO', _('Locality (City, Town, Village)')),
    ('AA', _('Administrative Area (Province,Municipality, County)')),
    ('NE', _('Neighborhood'))
)

SCIENTIFIC_DOMAINS = (
    ('--', _('My background is...')),
    ('MAT', _('Mathematics')),
    ('CIS', _('Computer and information sciences')),
    ('PHYS', _('Physical sciences')),
    ('CHES', _('Chemical sciences')),
    ('ERES', _('Earth and related environmental sciences')),
    ('BIS', _('Biological sciences')),
    ('ONS', _('Other natural sciences')),
    ('CIE', _('Civil engineering')),
    ('ELE', _('Electrical engineering, electronic')),
    ('EIE', _('engineering, information engineering')),
    ('MCE', _('Mechanical engineering')),
    ('CHE', _('Chemical engineering')),
    ('MAE', _('Materials engineering')),
    ('MEE', _('Medical engineering')),
    ('ENE', _('Environmental engineering')),
    ('ENB', _('Environmental biotechnology')),
    ('INB', _('Industrial Biotechnology')),
    ('NTE', _('Nano-technology')),
    ('OET', _('Other engineering and technologies')),
    ('BAM', _('Basic medicine')),
    ('CLM', _('Clinical medicine')),
    ('HSC', _('Health sciences')),
    ('HBI', _('Health biotechnology')),
    ('OMS', _('Other medical sciences')),
    ('AFF', _('Agriculture, forestry, and fisheries')),
    ('ADS', _('Animal and dairy science')),
    ('VES', _('Veterinary science')),
    ('AGB', _('Agricultural biotechnology')),
    ('OAS', _('Other agricultural sciences')),
    ('PSY', _('Psychology')),
    ('EB', _('Economics and business')),
    ('EDS', _('Educational sciences')),
    ('SOC', _('Sociology')),
    ('LAW', _('Law')),
    ('PS', _('Political Science')),
    ('SEG', _('Social and economic geography')),
    ('MC', _('Media and communications')),
    ('OSC', _('Other social sciences')),
    ('HA', _('History and archaeology')),
    ('LANG', _('Languages and literature')),
    ('PHIL', _('Philosophy, ethics and religion')),
    ('ART', _('Art (arts, history of arts, performing arts, music)')),
    ('OH', _('Other humanities'))
)

DATACOLLECTION_METHOD = (
    ('BSO', _('Backoffice / Service operations')),
    ('SUR', _('Survey')),
    ('HAR', _('Harvest')),
    ('IRE', _('Internal Research / Experiments'))
)

SOFTWARE_PACKAGE = (
    ('ACAS', 'AcaStat'),
    ('ADAS', 'ADaMSoft'),
    ('ANAL', 'Analyse-it'),
    ('AUGU', 'Auguri'),
    ('BIOS', 'BioStat'),
    ('BMDP', 'BMDP'),
    ('BRIS', 'BrightStat'),
    ('DATP', 'Dataplot'),
    ('DBAS', 'DBase'),
    ('DIF', 'DIF'),
    ('EASY', 'EasyReg'),
    ('EPIN', 'Epi Info'),
    ('EVIE', 'EViews'),
    ('GAUSS', 'GAUSS'),
    ('GOHE', 'Golden Helix'),
    ('GRPR', 'GraphPad Prism'),
    ('GRET', 'gretl'),
    ('JMP', 'JMP'),
    ('LIMP', 'Limdep'),
    ('MACA', 'MacAnova'),
    ('MAPL', 'Maple'),
    ('MATH', 'Mathematica'),
    ('MALA', 'MatLab'),
    ('MECA', 'MedCalc'),
    ('MITA', 'Minitab'),
    ('MOQE', 'modelQED'),
    ('NCSS', 'NCSS'),
    ('NSDS', 'NSDStat'),
    ('OPEP', 'OpenEpi'),
    ('ORIG', 'Origin'),
    ('OTHE', 'Other'),
    ('PART', 'Partek'),
    ('PRIM', 'Primer'),
    ('PSPP', 'PSPP'),
    ('R', 'R'),
    ('RCOM', 'R Commander'),
    ('RATS', 'RATS'),
    ('RKWA', 'RKWard'),
    ('SALS', 'SalStat'),
    ('SAS', 'SAS'),
    ('SHAZ', 'Shazam'),
    ('SOCR', 'SOCR'),
    ('SPLU', 'SPlus'),
    ('SPSS', 'SPSS'),
    ('STAT', 'Stata'),
    ('STACA', 'Statistica'),
    ('SUDA', 'SUDAAN'),
    ('TSP', 'TSP')
)

ANALYSIS_UNITS = (
    ('IN', _('Individual')),
    ('OR', _('Organization')),
    ('FA', _('Family')),
    ('FH', _('Family.HouseholdFamily')),
    ('HO', _('Household')),
    ('HU', _('HousingUnit')),
    ('EP', _('EventOrProcess')),
    ('GU', _('GeographicUnit')),
    ('TU', _('TimeUnit')),
    ('TE', _('TextUnit')),
    ('GR', _('Group')),
    ('OB', _('Object')),
    ('OT', _('Other'))
)

APPLICATION_TYPES = (
    ('--', _('Choose the type of item')),
    ('PU', _('Publication')),
    ('DA', _('Desktop Application')),
    ('SA', _('Mobile Application')),
    ('WA', _('Web Application')),
    ('WS', _('Web Service / API')),
    ('VI', _('Visualization image'))
)

PUBLICATION_TYPES = (
    ('--', _('Please choose a publication type')),
    ('AN', _('Annotation')),
    ('AR', _('Article / blog in Internet')),
    ('BO', _('Book')),
    ('BS', _('Book Section / Chapter')),
    ('CP', _('Conference Paper')),
    ('DIS', _('Dissertation')),
    ('IN', _('Internal or external report')),
    ('JA', _('Journal article (academic)')),
    ('JAN', _('Journal article (non academic)')),
    ('LP', _('Loose-leaf publications')),
    ('NA', _('Newspaper article')),
    ('OA', _('Online news agency article'))
)

DATASET_REQUESTS_TYPES = (
    ('', _('Please choose a request type..')),
    ('SD', _('Looking for a dataset')),
    ('CF', _('Conversion to other format')),
    ('DC', _('Data Cleansing')),
    ('ME', _('Metadata Enrichment')),
    ('DE', _('Data Enrichment')),
    ('SR', _('Snapshots of real-time data')),
    ('CD', _('Combination of datasets / Mash-ups')),
    ('DV', _('Data Verification')),
    ('FI', _('Freedom of Information Request')),
)